spring:
  cloud:
    gateway:
      routes:
        - id: mxun-chatai-open
          uri: lb://mxun-chatai
          predicates:
            - Path=/open/chatai/**
          filters:
            - RewritePath=/open/chatai/(?<segment>.*),/open/$\{segment}

        - id: mxun-chatai
          uri: lb://mxun-chatai
          predicates:
            - Path=/api/chatai/**
          filters:
            - RewritePath=/api/chatai/(?<segment>.*),/api/$\{segment}

        - id: mxun-chatai-third
          uri: lb://mxun-chatai
          predicates:
            - Path=/third/chatai/**
          filters:
            - RewritePath=/third/chatai/(?<segment>.*),/$\{segment}

        - id: mxun-auth-open
          uri: lb://mxun-auth
          predicates:
            - Path=/open/auth/**
          filters:
            - RewritePath=/open/auth/(?<segment>.*),/open/$\{segment}

        - id: mxun-sys-open
          uri: lb://mxun-sys
          predicates:
            - Path=/open/sys/**
          filters:
            - RewritePath=/open/sys/(?<segment>.*),/open/$\{segment}

        - id: mxun-sys
          uri: lb://mxun-sys
          predicates:
            - Path=/api/sys/**
          filters:
            - RewritePath=/api/sys/(?<segment>.*),/api/$\{segment}

        - id: mxun-art-open
          uri: lb://mxun-art
          predicates:
            - Path=/open/art/**
          filters:
            - RewritePath=/open/art/(?<segment>.*),/open/$\{segment}

        - id: mxun-art
          uri: lb://mxun-art
          predicates:
            - Path=/api/art/**
          filters:
            - RewritePath=/api/art/(?<segment>.*),/api/$\{segment}

        - id: mxun-mem-open
          uri: lb://mxun-mem
          predicates:
            - Path=/open/mem/**
          filters:
            - RewritePath=/open/mem/(?<segment>.*),/open/$\{segment}

        - id: mxun-mem
          uri: lb://mxun-mem
          predicates:
            - Path=/api/mem/**
          filters:
            - RewritePath=/api/mem/(?<segment>.*),/api/$\{segment}
