server:
  port: 7003
spring:
  application:
    name: mxun-sys
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - classpath:mybatis-flex-config.yml
      - classpath:redis.yml